PREFIX am: <http://www.imn.htwk-leipzig.de/~amuelle3/Data/Model/>
PREFIX ld: <http://leipzig-data.de/Data/Model/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?Ort ?grund ?gym ?ober ?kiga ?spielplatz ?schwimmbad ?sportplatz ?sporthalle
WHERE
{
  ?ort a ld:Ortsteil .
  ?ort rdfs:label ?Ort .
  OPTIONAL {
    SELECT ?ort (count(?g) as ?grund )
    WHERE {
        ?g rdf:type ld:Grundschule.
        ?g ld:hasAddress ?a.
        ?a ld:inOrtsteil ?ort.
    }
    GROUP BY ?ort  
  }
  OPTIONAL {
    SELECT ?ort (count(?g) as ?gym )
    WHERE {
        ?g rdf:type ld:Gymnasium.
        ?g ld:hasAddress ?a.
        ?a ld:inOrtsteil ?ort.
    }
    GROUP BY ?ort
  }
  OPTIONAL {
    SELECT ?ort (count(?g) as ?ober )
    WHERE {
        ?g rdf:type ld:Oberschule.
        ?g ld:hasAddress ?a.
        ?a ld:inOrtsteil ?ort.
    }
    GROUP BY ?ort
  }
  OPTIONAL {
    SELECT ?ort (count(?y) as ?kiga)
    WHERE {
      ?y a am:Kindergarten .
      ?y ld:inOrtsteil ?ort . 
    }
    GROUP BY ?ort
  }
  OPTIONAL {
    SELECT ?ort (count(?y) as ?spielplatz)
    WHERE {
      ?y a am:Spielplatz .
      ?y ld:inOrtsteil ?ort . 
    }
    GROUP BY ?ort
  }
  OPTIONAL {
    SELECT ?ort (count(?y) as ?schwimmbad)
    WHERE {
      ?y a am:Schwimmbad .
      ?y ld:inOrtsteil ?ort . 
    }
    GROUP BY ?ort
  }
  OPTIONAL {
    SELECT ?ort (count(?y) as ?sportplatz)
    WHERE {
      ?y a am:Sportplatz .
      ?y ld:inOrtsteil ?ort . 
    }
    GROUP BY ?ort
  }
  OPTIONAL {
    SELECT ?ort (count(?y) as ?sporthalle)
    WHERE {
      ?y a am:Sporthalle .
      ?y ld:inOrtsteil ?ort . 
    }
    GROUP BY ?ort
  }
}